server:
  port: 8081
spring:
  application:
    name: consumer
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: itcast
    password: twave1340281297
    listener:
      simple:
        preFetch: 1 #每次从队列中获取的消息数量，消费完成后再取
  #  management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: '*'
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: twave
    password: WgF!19981123
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  redis:
    host: 127.0.0.1
    port: 6379
    password: WgF!19981123
    database: 1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    mapped-statements-ordered: true # 开启查询返回Map结果有序
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
logging:
  level:
    root: info
    org.twave.Service1: debug
serviceName: consumer1